function Mdl = NaiveBayes(DATA,LABEL)
DATA = DATA(:,:);

            Mdl = fitcnb(...
                                            DATA, ...
                                            LABEL, ...
                                            'Kernel', 'Normal', ...
                                            'Support', 'Unbounded', ...
                                            'DistributionNames', repmat({'Kernel'}, 1, size(DATA,2)), ...  % 核Bayes这里改成Kernel
                                            'ClassNames', categorical({'1'; '2'}));
end

