function Mdl = SVM_GaussianKernel(DATA,LABEL)
DATA = DATA(:,:);
            Mdl = fitcsvm(...
                                DATA, ...
                                LABEL, ...
                                'KernelFunction', 'gaussian', ...
                                'PolynomialOrder', [], ...
                                'KernelScale', 34.85687216204889, ...
                                'BoxConstraint', 956.6482979442949, ...
                                'Standardize', false, ...
                                'ClassNames', categorical({'1'; '2'}));
end

