function Mdl = SVM_GaussianKernel_Auto(DATA,LABEL)
DATA = DATA(:,:);
params = hyperparameters('fitcsvm',DATA,LABEL);
params(1).Range = [1e3,1e6];
params(2).Range = [1e-3,1e5];
            Mdl = fitcsvm(...
                                DATA, ...
                                LABEL, ...
                                'KernelFunction', 'gaussian', ...
                                'ClassNames', categorical({'1'; '2'}), ...
                                'OptimizeHyperparameters', params, ...
                                'HyperparameterOptimizationOptions',struct('MaxObjectiveEvaluations',80,'UseParallel', true,'ShowPlots',false));
end

