function Mdl = Ensemble_AdaBoost(DATA,LABEL)
DATA = DATA(:,:);

            template = templateTree(...
                                            'MaxNumSplits', 3, ...
                                            'NumVariablesToSample', 'all');
            Mdl = fitcensemble(...
                                            DATA, ...
                                            LABEL, ...
                                            'Method', 'AdaBoostM1', ...
                                            'NumLearningCycles', 10, ...
                                            'Learners', template, ...
                                            'LearnRate', 0.007411898296579345, ...
                                            'ClassNames', categorical({'1'; '2'}));
end

