function Mdl = Tree(DATA,LABEL)
DATA = DATA(:,:);

            Mdl = fitctree(...
                                            DATA, ...
                                            LABEL, ...
                                            'SplitCriterion', 'gdi', ...
                                            'MaxNumSplits', 1, ...
                                            'Surrogate', 'off', ...
                                            'ClassNames', categorical({'1'; '2'}));
end

