function Mdl = KNN(DATA,LABEL)
DATA = DATA(:,:);

            Mdl = fitcknn(...
                                            DATA, ...
                                            LABEL, ...
                                            'Distance', 'Euclidean', ...
                                            'Exponent', [], ...
                                            'NumNeighbors', 64, ...
                                            'DistanceWeight', 'Equal', ...
                                            'Standardize', false, ...
                                            'ClassNames', categorical({'1'; '2'}));
end

