function Mdl = SVM_LinearKernel(DATA,LABEL)
DATA = DATA(:,:);

Mdl = fitcsvm(...
                                DATA, ...
                                LABEL, ...
                                'KernelFunction', 'linear', ...
                                'PolynomialOrder', [], ...
                                'KernelScale', 1, ...
                                'BoxConstraint', 0.02703443457599285, ...
                                'Standardize', true, ...
                                'ClassNames', categorical({'1'; '2'}));
end

